#
# This file contains configuration variables for drivers.
# It was generated by genhdrs.pl. Do not modify it.
#
package Driverhdrs;

$LAB = "datalab";
$SERVER_NAME = "cslab01.wheaton.edu";
$SERVER_PORT = 27340;
$COURSE_NAME = "csapp";
$AUTOGRADE_TIMEOUT = 0;
1;
